# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
[[redirects]]
  from = "/blog/EEVLz2X9vmSmZg6k6Dqx/end-to-end-machine-learning-using-containerization"
  to = "/blog/end-to-end-machine-learning-using-containerization"
  status = 301
  force = false
[[redirects]]
  from = "/blog/Oj0pNxBE3JsJB02E2KOj/kubernetized-machine-learning-and-ai-using-kubeflow"
  to = "/blog/kubernetized-machine-learning-and-ai-using-kubeflow"
  status = 301
  force = false
[[redirects]]
  from = "https://developer.hpe.com/blog/0N796xBvYxcyGq8Yo35N/event-driven-microservices-architecture-patterns-and-examples"
  to = "/blog/event-driven-microservices-architecture-patterns-and-examples"
  status = 301
  force = false
[[redirects]]
  from = "/events"
  to = "/platform"
  status = 301
  force = false
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  #[dev] 
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
